### ISSUE TITLE
gitignore option incompatible with objectMode option

### ISSUE THREAD

**Issue by alexander-akait** [sindresorhus/globby#145]
Reproducible example:

```js
const paths = await globby(
  '/path/to/directory/**/*', 
  {
    objectMode: true,
    gitignore: true
  }
);

console.log(paths);
```

Output:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

  at ensureAbsolutePathForCwd (node_modules/globby/gitignore.js:48:11)
  at p (node_modules/globby/gitignore.js:60:55)
  at arrayUnion.filter.path_ (node_modules/globby/index.js:135:47)
    at Array.filter (<anonymous>)
  at module.exports (node_modules/globby/index.js:135:30)

```

**Comment by gregbenz** [comment]
This same issue seems to be affecting **copy-webpack-plugin** (per @evilebottnawi: https://github.com/webpack-contrib/copy-webpack-plugin/issues/496). Results in webpack error at build: "_ERROR in The "path" argument must be of type string. Received an instance of Object_" (the error does not anything beyond that to find the source of the failure).

The following plugins options in webpack.config.js will fail when gitignore is true:

```
plugins: [
	new CopyPlugin({
		patterns: [
			{
				from: './', 
				to: '../dist/',
				context: './src/',
				globOptions: {
					dot: true,
					gitignore: true, //In "copy-webpack-plugin": "^6.0.3", causes: ERROR in The "path" argument must be of type string. Received an instance of Object
					ignore: ['**/*.ts', '**/*.tif*', '**/*.tif', '**/*.md', '**/*.js', '**/libs/**', '**/*.doc'],
				},
			},
		],
	}),
],
```

**Comment by xiaoweibaniu** [comment]
so, i want to know how to solve the problem now,please?
